### ISSUE TITLE
[BUG] pip

### ISSUE THREAD

**Issue by jesse-wei** [NIRALUser/NeuroRuler#58]
pip upload is bugged

Our program assumes the user has cloned the repo so directories like NeuroRuler/GUI/themes and NeuroRuler/GUI/static exist. Also, files like config.json.

However, after installing via pip and using via Python terminal, these files will not exist.

Therefore, these files need to be packaged into the distribution (already done on the pip branch). File accesses and the importlib statement in NeuroRuler/GUI/main.py need to access the files packaged into the distribution if they don't exist locally.

```text
if file exists locally
    use it
else
    use file packaged into distribution
```

This link shows how to access packaged files. https://medium.com/@vuillaut/python-package-and-access-data-in-your-module-d05e72f58785

**Comment by mlouielu** [comment]
Take a look at: https://setuptools.pypa.io/en/latest/userguide/datafiles.html

Should add a test before upload to pypi. Usually will add this test after packaging in the CI.

**Comment by jesse-wei** [comment]
Thanks, Louie!

Makes sense. I will add `needs: test` to the [pypi.yml](.github/workflows/pypi.yml) action.

**Comment by jesse-wei** [comment]
Resolved.
