### ISSUE TITLE
[FEATURE] Use `CITATION.cff` to manage citation reference

### ISSUE THREAD

**Issue by mlouielu** [NIRALUser/NeuroRuler#96]
We can use `CITATION.cff` to manage citation reference.

We can use [cffinit](https://citation-file-format.github.io/cff-initializer-javascript) to generate the file.

GitHub [support cite this repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) using this file.

**Comment by jesse-wei** [comment]
Thanks Louie!
