### ISSUE TITLE
[FEATURE] Enable mypy check in pre-commit-hook

### ISSUE THREAD

**Issue by mlouielu** [NIRALUser/NeuroRuler#97]
Since we have type hints, I would also suggest to enable mypy check in pre-commit-hook.

Setup example, I put mypy setting in `pyproject.toml`: https://github.com/mmwave-capture-std/mmwave-capture-std/blob/8f3332814aba442003e0a3e103629d2331c30f7d/.pre-commit-config.yaml#L15

**Comment by jesse-wei** [comment]
404a80d
