### ISSUE TITLE
Add year in license

### ISSUE THREAD

**Issue by mlouielu** [NIRALUser/NeuroRuler#98]
Current license text: https://github.com/NIRALUser/NeuroRuler/blob/35c41ba52c4c1aef41c88eb5b00d01a26cd98a7e/LICENSE#L3

According to [OSI](https://opensource.org/license/mit/) and [SPDX](https://spdx.org/licenses/MIT.html), MIT license should have `<year>` and `<copyright holders>`, but we don't have `<year>` in it.

**Comment by jesse-wei** [comment]
840e89b
